MESSAGE 1
It's Dangerous to go alone!  Take this!

With that, the old man drops a short sword in front of you.
END_MESSAGE

MESSAGE 2
You walk down the dark forested path to come to yet another area which leads
out into all four compass directions.
END_MESSAGE

MESSAGE 3
As you walk through the dark forested path you finally come to a clearing!

You made it out of the lost woods!
END_MESSAGE

MESSAGE 4
You ascend up the mountain stairs...
END_MESSAGE

MESSAGE 5
I have nothing more to say or give you.  You may leave.
END_MESSAGE

MESSAGE 6
"Buy something will ya!", Exclaims the merchant.

Unfortunately currency and shops are yet to be implemented here.
END_MESSAGE

MESSAGE 7
The river here appears to wide to cross, and the only way to go is back east.
There does appear to be what looks like a cave entrance on the other side of
the river.
END_MESSAGE

MESSAGE 8
The river here appears to wide to cross, and there appears to be a cave
in the cliff walls here.  It seems the only way to go is north.
END_MESSAGE

MESSAGE 9
It is impossible to cross a river this wide to go that direction, so just
forget about it!
END_MESSAGE

MESSAGE 10
The old woman remains quiet and doesn't say a word.
END_MESSAGE

MESSAGE 11
The old woman begins to speak, "Visit the old man at the grave" she says.
END_MESSAGE

MESSAGE 12
The old man speaks, "Take this letter and show it to the old woman."

With that, the old man gives you a blue letter.
END_MESSAGE

MESSAGE 13
You show the old woman the blue letter, she smiles.

"Here, take this red medicine with you!", she said as she hands you a bottle
filled with a red liquid.
END_MESSAGE

MESSAGE 14
You hop onto the raft and set sail for the distant island...
END_MESSAGE

MESSAGE 15
The old woman speaks, "Go North, West, South, West in the Lost Woods"
END_MESSAGE

MESSAGE 16
The old man says, "Master using it, and you can have this!"
END_MESSAGE

MESSAGE 17

The old man then hands you the White Sword!
END_MESSAGE

MESSAGE 18

The old man then hands you the Magical Sword!
END_MESSAGE

MESSAGE 19
You walk south down the narrow forest path.  The path continue west into
a clearing that you now find yourself in.
END_MESSAGE

MESSAGE 20
You put both of your hands on the boulder, it begins to move, if almost by
magic.  A set of stairs forms in the ground as if out of nowhere.

You descend down the stairs into the cavern below...
END_MESSAGE

MESSAGE 21
You put both of your hands on the boulder and begin to push with all your
might...  The boulder just does not want to budge.
END_MESSAGE

MESSAGE 22
Perhaps you should try wearing that bracelet you found and give it another try.
END_MESSAGE

MESSAGE 23
As you begin to push the Armos out of the way, it spins to life and begins
attacking you!  With a quick slice of your sword, you destroy it.

After destroying it, it leaves behind what appears to be a bracelet of
some kind.  Curious, you pick it up and take it with you.
END_MESSAGE

MESSAGE 24
As you begin to push the Armos out of the way, it spins to life and begins
attacking you!  With a quick slice of your sword, you destroy it.

After destroying it, a set of stairs is revealed to have been underneath it.
Curious, you go descend down the stairs...
END_MESSAGE

MESSAGE 25
Since this game engine does not support a currency, I'll just give you the
blue ring!

You obtained the Blue Ring!
END_MESSAGE

MESSAGE 26
The old woman begins to speak, "Go Up, Up, the mountain ahead."
END_MESSAGE

MESSAGE 27
Since this game engine does not support a currency, I'll just give you the
bomb!

You obtained the Bomb!
END_MESSAGE

MESSAGE 28
As you try to cross the river to the other side, you realize how unsafe it is
and that you probably should not try, or it could easily spell your sudden
death.
END_MESSAGE

MESSAGE 29
You place the step ladder across the river and carefully cross the river over
top of the step ladder.  You made it!
END_MESSAGE

MESSAGE 30
You take out the red candle and burn a nearby bush...

The bush begins to burn away, eventually revealing a set of stairs beneath the
forest.  You descend down the stairs...
END_MESSAGE

MESSAGE 31
You set the big bomb down in front of the large rock formation and set the
fuse, then quickly take cover...

BOOOOOM!!!!

A large hole is now in the rock formation, large enough for a Hylian to walk
through.
END_MESSAGE

MESSAGE 32
As you walk north into the Triforce of Wisdom checkpoint, all the pieces of
the Triforce of Wisdom you were carrying fuse together to form a complete
Triforce of Wisdom.  You hold up the entire Triforce above your head, and
the magical barrier that once existed disappears, allowing you to go forward.
END_MESSAGE
